# Usage:
# micromamba create --name mqc-env --file environment.yml
name: mqc-env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - pyg
  - defaults
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - pydantic
  - pyyaml
  - h5py
  - packaging
  - pytorch=2.6.0
  - pytorch-cuda=12.4
  - pytorch-cluster
  - pip
  # aimnet2calc dependencies
  - ase
  - openbabel
  - matplotlib
  - scikit-learn
  - sympy
  - autograd
  - dask
  - distributed
  - fabric
  - jinja2
  - joblib
  - natsort
  - psutil
  - rmsd
  - pip:
    - --index-url https://download.pytorch.org/whl/cu124
    - rdkit
    - pysisyphus
    - gpu4pyscf-cuda12x
    - cutensor-cu12
    - torch==2.6.0
    - loguru
    - tqdm
    - snowflake-snowpark-python