[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mqc_pipeline"
version = "0.1.0"
authors = [
    { name="Renke Huang", email="renke.huang@ses.ai" },
]
description = "High-throughput molecular quantum chemistry (MQC) pipeline"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    'numpy >= 1.20.0',
    "scipy>=1.6.0",
    'pydantic >= 1.10',
    'PyYAML >= 6.0',
    'h5py >= 3.0',
    'rdkit',
    'ase',
    "pyscf==2.8.0",
    "geometric",
]
license = {text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["quantum chemistry", "computational chemistry", "chemoinformatics"]

[project.urls]
homepage = "https://github.com/Solid-Energy-Systems/mqc_pipeline"

[project.scripts]
RUN = "scripts.main:main" # Maps the command to the main function in modules/main.py

[tool.setuptools.packages.find]
where = ["."]

[project.optional-dependencies]
gpu = [
    "cupy-cuda12x>=13.0,!=13.4.0",
    "gpu4pyscf-cuda12x>=1.4.0",
    "gpu4pyscf-libxc-cuda12x==0.5",
    "cutensor-cu12>=2.2.0",
]
dev = [
    "pytest>=7.0.0",
    # "pytest-cov>=3.0.0",
    # "pytest-env",
]

[tool.pytest.ini_options]
# addopts = "--cov=mqc_pipeline"
addopts = "--durations=10 --durations-min=0"
testpaths = ["tests"]

[tool.pytest.ini_options.env]
PYTHONDONTWRITEBYTECODE = "1"

[tool.coverage.run]
omit = [
    "*/__init__.py",
    "*/tests/*",
]

