name: Run Unit Tests

# Defines the events that trigger the workflow.
# Here, the workflow runs on push and pull requests to the main branch.
on:
  push:
    paths:
      - 'mqc_pipeline/**'  # Only trigger when files in the mqc_pipeline directory are changed
      - 'tests/**'         # Include changes to test files

# jobs: Defines the tasks that the workflow will execute.
# Here, there is a single job named test.
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version

      # Step 3: Install the package in editable mode (.) along with test dependencies
      # defined in pyproject.toml
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run pytest
        run: pytest --maxfail=5 --disable-warnings
